# Generated by Django 3.2.25 on 2025-02-13 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('singer', '0001_initial'),
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('length', models.DecimalField(decimal_places=2, max_digits=5)),
                ('mood', models.CharField(choices=[('sad', 'Sad'), ('romantic', 'Romantic'), ('love', 'Love'), ('fun', 'Fun'), ('happy', 'Happy'), ('motivational', 'Motivational'), ('heartbreak', 'Heartbreak')], default='happy', max_length=20)),
                ('genre', models.CharField(choices=[('rock', 'Rock'), ('pop', 'Pop'), ('hip-hop', 'Hip-Hop'), ('blues', 'Blues')], default='pop', max_length=20)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='movies.movies')),
                ('singer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='singer.singer')),
            ],
        ),
    ]
