# Generated by Django 4.2.19 on 2025-04-14 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('singer', '__first__'),
        ('movies', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('length', models.DecimalField(decimal_places=2, max_digits=5)),
                ('mood', models.CharField(choices=[('sad', 'Sad'), ('romantic', 'Romantic'), ('love', 'Love'), ('fun', 'Fun'), ('happy', 'Happy'), ('motivational', 'Motivational'), ('heartbreak', 'Heartbreak')], default='happy', max_length=20)),
                ('genre', models.CharField(choices=[('rock', 'Rock'), ('pop', 'Pop'), ('hip-hop', 'Hip-Hop'), ('blues', 'Blues')], default='pop', max_length=20)),
                ('lyrics', models.TextField(default='Lyrics are not available')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='movies.movie')),
                ('singer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='singer.singer')),
            ],
        ),
    ]
