# Generated by Django 3.2.25 on 2025-02-13 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('singer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='singer',
            name='age',
            field=models.IntegerField(default=20),
        ),
        migrations.AddField(
            model_name='singer',
            name='followers',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='singer',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='singer',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
