# Generated by Django 4.2.19 on 2025-04-15 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_subscriber',
            field=models.BooleanField(default=False),
        ),
    ]
