# Generated by Django 4.2.19 on 2025-04-14 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('type', models.CharField(choices=[('hollywood', 'Hollywood'), ('bollywood', 'Bollywood'), ('tollywood', 'Tollywood'), ('punjabi', 'Punjabi')], default='bollywood', max_length=100)),
                ('cast', models.TextField(default='Tell use the actors and acctresses')),
                ('length', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('release_date', models.DateTimeField(null=True)),
                ('description', models.TextField(default='Tell us something about movies')),
            ],
        ),
    ]
