# Generated by Django 3.2.25 on 2025-02-13 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='cast',
            field=models.TextField(default='Tell use the actors and acctresses'),
        ),
        migrations.AddField(
            model_name='movies',
            name='description',
            field=models.TextField(default='Tell us something about movies'),
        ),
        migrations.AddField(
            model_name='movies',
            name='length',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='movies',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='movies',
            name='release_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='movies',
            name='type',
            field=models.CharField(choices=[('hollywood', 'Hollywood'), ('bollywood', 'Bollywood'), ('tollywood', 'Tollywood'), ('punjabi', 'Punjabi')], default='bollywood', max_length=100),
        ),
    ]
