# Generated by Django 3.2.25 on 2025-02-13 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0002_song_lyrics'),
        ('movies', '0002_auto_20250213_1649'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Movies',
            new_name='Movie',
        ),
    ]
